name: Pull Request Workflow
on:
  pull_request:

jobs:
  validate:
    name: Validate Release Label
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform -chdir=apps fmt -check
        continue-on-error: false

      - name: Read images json
        id: read-json
        run: |
          echo cat ./images.json | jq '.ui'

  # echo "::set-output name=images::cat ./images.json | jq '.ui'"

  # echo ${{ fromJson(steps.read-json.outputs.images) }}
  # echo ${{ toJson(steps.read-json.outputs.images) }}

  # UI="${{ fromJson(env.IMAGES).version }}"
  # echo $UI the value of ui

# - name: Configure AWS credentials
#   uses: aws-actions/configure-aws-credentials@v1
#   with:
#     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#     aws-region: us-east-1

# - name: Terraform Init
#   id: init
#   run: terraform init

# - name: Terraform Validate
#   id: validate
#   run: terraform validate -no-color ar

# - name: Terraform Plan
#   id: plan
#   run: terraform plan -no-color
#   continue-on-error: false

# check the images exist
# add a new tag to the image on approval
# plan should post a comment with the plan
# command "deploy and squash"
