name: Pull Request Workflow
on:
  pull_request:

jobs:
  validate:
    name: Validate Release Label
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Read images json
        id: images
        run: |
          JSON=`echo cat ./images.json | jq ".ui"`
          echo aaaaaa $JSON
          echo "::set-output name=ui::$JSON"

      - name: Terraform fmt
        id: fmt
        run: terraform -chdir=apps fmt -check
        continue-on-error: false

      - name: Terraform Init
        id: init
        run: terraform -chdir=apps init

      - name: Terraform Validate
        id: validate
        run: |
          echo ${{ steps.images.outputs.ui}}
    # terraform -chdir=apps validate -no-color -var="ecr_image='${{ steps.images.outputs.ui}}'"

# - name: Terraform Plan
#   id: plan
#   run: terraform plan -no-color
#   continue-on-error: false

# check the images exist
# add a new tag to the image on approval
# plan should post a comment with the plan
# command "deploy and squash"
